# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-25 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('billing', '0002_labbill_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='coupons.Coupon'),
        ),
        migrations.AlterField(
            model_name='labbill',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 17, 43, 21, 792000)),
        ),
    ]
