# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-27 06:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210525_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='paid',
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(b'unpaid', b'UNPAID'), (b'paid', b'PAID')], default=1),
        ),
        migrations.AlterField(
            model_name='labbill',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 9, 33, 31, 882000)),
        ),
    ]
