# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TabibuNet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default=b'Reason for admission')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[(b'active', b'ACTIVE'), (b'closed', b'CLOSED')], default=b'active', max_length=50)),
                ('slug', models.SlugField(default=b'admission')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('medication', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=30)),
                ('instruction', models.CharField(max_length=200)),
                ('refill', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='inpatient.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Medtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('examination', models.TextField()),
                ('diagnosis', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_test', to='inpatient.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Obstetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('examination', models.TextField()),
                ('diagnosis', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Obs_Gyn', to='inpatient.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='ObstetricsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('medical_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstetric_images', to='inpatient.Obstetrics')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(b'children', b'CHILDREN'), (b'male', b'MALE'), (b'female', b'FEMALE')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='labimage',
            name='medical_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_images', to='inpatient.Medtest'),
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_bed', to='inpatient.Ward'),
        ),
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_admitted', to='inpatient.Bed'),
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_admission', to='TabibuNet.Patient'),
        ),
    ]
