# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-18 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0003_auto_20200318_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_admitted', to='inpatient.Bed'),
        ),
    ]
