# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-18 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0004_auto_20200318_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='occupied',
        ),
    ]
