# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-19 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0005_remove_bed_occupied'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('medication', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=30)),
                ('instruction', models.CharField(max_length=200)),
                ('refill', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='inpatient.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Medtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('examination', models.TextField()),
                ('diagnosis', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_test', to='inpatient.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Obstetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('examination', models.TextField()),
                ('diagnosis', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Obs_Gyn', to='inpatient.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='ObstetricsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('medical_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstetric_images', to='inpatient.Obstetrics')),
            ],
        ),
        migrations.AddField(
            model_name='labimage',
            name='medical_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_images', to='inpatient.Medtest'),
        ),
    ]
