# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-06 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0006_auto_20200319_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='active',
        ),
        migrations.AddField(
            model_name='admission',
            name='slug',
            field=models.SlugField(default=b'admission'),
        ),
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[(b'active', b'ACTIVE'), (b'closed', b'CLOSED')], default=b'active', max_length=50),
        ),
    ]
