# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-06 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0007_auto_20200406_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='discharge_date',
            field=models.DateTimeField(null=True),
        ),
    ]
