# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-19 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inpatient', '0009_admission_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_admission', to='TabibuNet.Patient'),
        ),
    ]
