# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='members')),
            ],
        ),
    ]
