# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('job', models.CharField(blank=True, max_length=50, verbose_name='Work Title')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='members')),
                ('added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-added',),
                'verbose_name_plural': 'Team',
            },
        ),
    ]
