# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-29 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('applied', models.DateTimeField(auto_now_add=True, verbose_name='registered on')),
                ('aboutus', models.TextField(blank=True, verbose_name='how did you find out about us?')),
            ],
            options={
                'ordering': ('-applied',),
            },
        ),
    ]
