# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('TabibuNet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TabibuNet.Visit')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
