# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-06-18 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 14, 58, 6, 638000)),
        ),
    ]
