# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-16 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 8, 39, 54, 358000)),
        ),
    ]
