# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-16 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 18, 19, 31, 785000)),
        ),
    ]
