# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-16 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0002_auto_20210516_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 18, 20, 14, 460000)),
        ),
    ]
