# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-06-18 19:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0002_auto_20200618_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 22, 2, 59, 607000)),
        ),
    ]
