# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-03-18 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0002_auto_20200316_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 13, 45, 18, 435000)),
        ),
    ]
