# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-08-06 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0003_auto_20200618_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 20, 35, 8, 30000)),
        ),
    ]
