# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-16 17:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0004_auto_20210516_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 20, 24, 29, 101000)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, b'Reception'), (2, b'Wait_for_provider'), (3, b'Provider'), (4, b'Dental'), (5, b'Waiting_for_lab'), (6, b'Lab'), (7, b'Wait_for_pharmacy'), (8, b'Pharmacy'), (9, b'Billing'), (10, b'Ready_to_close'), (11, b'Closed')], default=1),
        ),
    ]
