# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-16 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0005_auto_20210516_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 0, 33, 0, 634000)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(1, b'Reception'), (2, b'Wait_for_provider'), (3, b'Provider'), (4, b'Wait_for_dental'), (5, b'Dental'), (6, b'Waiting_for_lab'), (7, b'Lab'), (8, b'Wait_for_pharmacy'), (9, b'Pharmacy'), (10, b'Billing'), (11, b'Ready_to_close'), (12, b'Closed')], default=1),
        ),
    ]
