# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-19 05:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0006_auto_20210517_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=30)),
                ('instruction', models.CharField(max_length=200)),
                ('refill', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='refill',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='strength',
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(b'undelivered', b'UNDELIVERED'), (b'delivered', b'DELIVERED')], default=1),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 8, 52, 7, 964000)),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='TabibuNet.Prescription'),
        ),
    ]
