# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-19 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0007_auto_20210519_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 10, 20, 14, 865000)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='TabibuNet.Visit'),
        ),
    ]
