# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2021-05-24 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0008_auto_20210519_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AlterField(
            model_name='labtest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 15, 33, 27, 152000)),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
