# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-06 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0008_auto_20200319_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 9, 48, 10, 586000)),
        ),
    ]
