# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-07 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0010_auto_20200406_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 13, 9, 41, 376000)),
        ),
    ]
