# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-13 16:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0011_auto_20200407_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 19, 19, 7, 648000)),
        ),
    ]
