# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-04-19 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TabibuNet', '0012_auto_20200413_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 20, 38, 53, 44000)),
        ),
    ]
